// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TehnologijeWebaProjektPokemonAndrijaFiringer.Data;

#nullable disable

namespace TehnologijeWebaProjektPokemonAndrijaFiringer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260807190435_AddBattleEffectHierarchy")]
    partial class AddBattleEffectHierarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MoveOwnedPokemon", b =>
                {
                    b.Property<int>("MovesId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnedPokemonId")
                        .HasColumnType("integer");

                    b.HasKey("MovesId", "OwnedPokemonId");

                    b.HasIndex("OwnedPokemonId");

                    b.ToTable("MoveOwnedPokemon");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EffectType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PokemonSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("StageChange")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusInteraction")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetStat")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.BattleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BattleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVictory")
                        .HasColumnType("boolean");

                    b.Property<string>("TurnsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BattleLogs");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ToSpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromSpeciesId");

                    b.HasIndex("ToSpeciesId");

                    b.ToTable("Evolutions");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.HeldItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeldItems");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplyStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("EffectType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PP")
                        .HasColumnType("integer");

                    b.Property<int?>("PokemonSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryEffectChance")
                        .HasColumnType("integer");

                    b.Property<int?>("StageChange")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetStat")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.OwnedPokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int?>("HeldItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInTeam")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("HeldItemId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnedPokemon");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseGender")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHp")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpecialAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpecialDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryType")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PokemonSpecies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MoveOwnedPokemon", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Move", null)
                        .WithMany()
                        .HasForeignKey("MovesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.OwnedPokemon", null)
                        .WithMany()
                        .HasForeignKey("OwnedPokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Ability", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", null)
                        .WithMany("Abilities")
                        .HasForeignKey("PokemonSpeciesId");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.BattleLog", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", "User")
                        .WithMany("BattleLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Evolution", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", "FromSpecies")
                        .WithMany("Evolutions")
                        .HasForeignKey("FromSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", "ToSpecies")
                        .WithMany()
                        .HasForeignKey("ToSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSpecies");

                    b.Navigation("ToSpecies");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Move", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", null)
                        .WithMany("Moves")
                        .HasForeignKey("PokemonSpeciesId");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.OwnedPokemon", b =>
                {
                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.Ability", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.HeldItem", "HeldItem")
                        .WithMany()
                        .HasForeignKey("HeldItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", "Species")
                        .WithMany("OwnedPokemon")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", "User")
                        .WithMany("OwnedPokemon")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("HeldItem");

                    b.Navigation("Species");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BattleLogs");

                    b.Navigation("OwnedPokemon");
                });

            modelBuilder.Entity("TehnologijeWebaProjektPokemonAndrijaFiringer.Models.Entities.PokemonSpecies", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Evolutions");

                    b.Navigation("Moves");

                    b.Navigation("OwnedPokemon");
                });
#pragma warning restore 612, 618
        }
    }
}
